// =============================================================================
// Script Autocomplete
// =============================================================================
//
// Autocomplete functionality for the Luau script editor.
// Shows contextual suggestions as the user types in the script panel.
//
// This is a UI-ONLY module. Autocomplete suggestions are generated by the
// C++ Luau autocomplete engine via the WASM bridge.
//
// Key responsibilities:
// - Create and manage autocomplete popup element
// - Show/hide popup with suggestions
// - Keyboard navigation (up/down/enter/escape)
// - Accept suggestion and insert text
// - Position popup near cursor
// - Sort suggestions by type correctness
//
// =============================================================================

import type { AutocompleteResult, AutocompleteSuggestion } from "./client-types";
import { getMenuStateManager } from "./menu-state";

// =============================================================================
// Types
// =============================================================================

/** Configuration for ScriptAutocomplete */
export interface AutocompleteConfig {
  /** The textarea element to provide autocomplete for */
  editor: HTMLTextAreaElement;
  /** Container element to append popup to */
  panel: HTMLElement;
  /** Function to get autocomplete suggestions from C++ */
  getAutocomplete: (source: string, line: number, column: number) => Promise<AutocompleteResult>;
}

// =============================================================================
// ScriptAutocomplete Class
// =============================================================================

/**
 * ScriptAutocomplete manages the autocomplete UI for the script editor.
 *
 * Responsibilities:
 * - Creating and positioning the popup
 * - Displaying suggestions with icons and type info
 * - Handling keyboard navigation
 * - Inserting accepted completions
 */
export class ScriptAutocomplete {
  // =========================================================================
  // Dependencies
  // =========================================================================

  private editor: HTMLTextAreaElement;
  private panel: HTMLElement;
  private getAutocomplete: (source: string, line: number, column: number) => Promise<AutocompleteResult>;

  // =========================================================================
  // State
  // =========================================================================

  private popup: HTMLElement | null = null;
  private items: AutocompleteSuggestion[] = [];
  private selectedIndex: number = 0;
  private visible: boolean = false;
  private debounceTimer: ReturnType<typeof setTimeout> | null = null;
  private userNavigated: boolean = false; // True if user navigated with arrows

  // =========================================================================
  // Constructor
  // =========================================================================

  constructor(config: AutocompleteConfig) {
    this.editor = config.editor;
    this.panel = config.panel;
    this.getAutocomplete = config.getAutocomplete;

    this.createPopup();
    this.setupEventListeners();

    // Register with MenuStateManager
    getMenuStateManager().registerMenu("scriptAutocomplete", () => this.hide());
  }

  // =========================================================================
  // Public API
  // =========================================================================

  /**
   * Check if autocomplete popup is visible
   */
  isVisible(): boolean {
    return this.visible;
  }

  /**
   * Handle keyboard events. Returns true if the key was handled.
   */
  handleKey(e: KeyboardEvent): boolean {
    if (!this.visible) return false;

    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        this.userNavigated = true;
        this.selectItem(
          Math.min(this.selectedIndex + 1, this.items.length - 1)
        );
        return true;

      case "ArrowUp":
        e.preventDefault();
        this.userNavigated = true;
        this.selectItem(
          Math.max(this.selectedIndex - 1, 0)
        );
        return true;

      case "Tab":
        // Tab always accepts (common IDE behavior)
        e.preventDefault();
        this.accept();
        return true;

      case "Enter":
        // Enter only accepts if user has navigated with arrows
        // Otherwise, let Enter insert a newline (fall through)
        if (this.userNavigated) {
          e.preventDefault();
          this.accept();
          return true;
        }
        // Hide autocomplete but don't prevent Enter
        this.hide();
        return false;

      case "Escape":
        e.preventDefault();
        this.hide();
        return true;

      default:
        return false;
    }
  }

  /**
   * Hide the autocomplete popup
   */
  hide(): void {
    if (!this.popup) return;
    this.popup.style.display = "none";
    this.visible = false;
    this.items = [];
    getMenuStateManager().closeMenu("scriptAutocomplete");
  }

  /**
   * Trigger autocomplete (debounced)
   */
  triggerDebounced(): void {
    // Cancel any pending request
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
    }

    this.debounceTimer = setTimeout(() => {
      this.debounceTimer = null;
      this.trigger();
    }, 100);
  }

  // =========================================================================
  // Private Methods - Setup
  // =========================================================================

  /**
   * Create the autocomplete popup element
   */
  private createPopup(): void {
    this.popup = document.createElement("div");
    this.popup.className = "autocomplete-popup";
    this.popup.style.display = "none";
    // Append to panel so it's positioned relative to the editor
    this.panel.appendChild(this.popup);
  }

  /**
   * Set up event listeners
   */
  private setupEventListeners(): void {
    // Trigger autocomplete as user types (debounced)
    this.editor.addEventListener("input", () => {
      this.triggerDebounced();
    });

    // Hide autocomplete when editor loses focus
    this.editor.addEventListener("blur", () => {
      // Small delay to allow click on autocomplete item
      setTimeout(() => {
        if (!this.editor.contains(document.activeElement)) {
          this.hide();
        }
      }, 100);
    });
  }

  // =========================================================================
  // Private Methods - Cursor Position
  // =========================================================================

  /**
   * Get the current cursor position as (line, column) - 0-indexed
   */
  private getCursorPosition(): { line: number; column: number } {
    const value = this.editor.value;
    const cursorPos = this.editor.selectionStart;

    // Count lines before cursor
    const textBeforeCursor = value.substring(0, cursorPos);
    const lines = textBeforeCursor.split("\n");
    const line = lines.length - 1;
    const column = (lines[lines.length - 1] ?? "").length;

    return { line, column };
  }

  /**
   * Get pixel position for cursor (for popup placement)
   */
  private getCursorPixelPosition(): { x: number; y: number } {
    const value = this.editor.value;
    const cursorPos = this.editor.selectionStart;

    // Count lines and get column
    const textBeforeCursor = value.substring(0, cursorPos);
    const lines = textBeforeCursor.split("\n");
    const lineIndex = lines.length - 1;
    const column = (lines[lines.length - 1] ?? "").length;

    // Approximate character dimensions (monospace font)
    const lineHeight = 19.5; // 13px * 1.5 line-height
    const charWidth = 7.8; // approximate for 13px monospace

    // Account for padding (12px) and line numbers gutter (40px)
    const editorRect = this.editor.getBoundingClientRect();
    const x = editorRect.left + 12 + column * charWidth;
    const y = editorRect.top + 12 + (lineIndex + 1) * lineHeight - this.editor.scrollTop;

    return { x, y };
  }

  // =========================================================================
  // Private Methods - Trigger & Show
  // =========================================================================

  /**
   * Trigger autocomplete at current cursor position
   */
  private async trigger(): Promise<void> {
    const source = this.editor.value;
    const { line, column } = this.getCursorPosition();

    try {
      const result = await this.getAutocomplete(source, line, column);
      if (result.suggestions.length > 0) {
        this.show(result.suggestions);
      } else {
        this.hide();
      }
    } catch {
      this.hide();
    }
  }

  /**
   * Show autocomplete popup with suggestions
   */
  private show(suggestions: AutocompleteSuggestion[]): void {
    if (!this.popup) return;

    // Sort suggestions: type-correct first, then correctFunctionResult, then rest
    const sortedSuggestions = this.sortByTypeCorrectness(suggestions);

    this.items = sortedSuggestions;
    this.selectedIndex = 0;
    this.visible = true;
    this.userNavigated = false; // Reset navigation state for new suggestions
    getMenuStateManager().openMenu("scriptAutocomplete");

    // Build popup content
    this.popup.innerHTML = "";
    sortedSuggestions.forEach((suggestion, index) => {
      const item = document.createElement("div");
      item.className = "autocomplete-item" + (index === 0 ? " selected" : "");
      // Add type-correct class for visual highlighting
      if (suggestion.typeCorrect === "correct") {
        item.classList.add("type-correct");
      } else if (suggestion.typeCorrect === "correctFunctionResult") {
        item.classList.add("type-correct-fn");
      }
      item.dataset.index = String(index);

      // Kind icon
      const icon = document.createElement("span");
      icon.className = "autocomplete-icon";
      icon.textContent = this.getKindIcon(suggestion.kind);
      item.appendChild(icon);

      // Label
      const label = document.createElement("span");
      label.className = "autocomplete-label";
      label.textContent = suggestion.label;
      if (suggestion.deprecated) {
        label.classList.add("deprecated");
      }
      item.appendChild(label);

      // Detail (type info)
      if (suggestion.detail) {
        const detail = document.createElement("span");
        detail.className = "autocomplete-detail";
        detail.textContent = suggestion.detail;
        item.appendChild(detail);
      }

      // Type correctness indicator
      if (suggestion.typeCorrect === "correct" || suggestion.typeCorrect === "correctFunctionResult") {
        const indicator = document.createElement("span");
        indicator.className = "autocomplete-type-indicator";
        indicator.textContent = "✓";
        indicator.title = suggestion.typeCorrect === "correct"
          ? "Matches expected type"
          : "Returns expected type";
        item.appendChild(indicator);
      }

      // Click handler
      item.addEventListener("mousedown", (e) => {
        e.preventDefault(); // Prevent blur
        this.accept(index);
      });

      // Hover handler
      item.addEventListener("mouseenter", () => {
        this.selectItem(index);
      });

      this.popup!.appendChild(item);
    });

    // Position popup near cursor
    const { x, y } = this.getCursorPixelPosition();
    const panelRect = this.panel.getBoundingClientRect();

    // Position relative to panel
    this.popup.style.left = `${x - panelRect.left}px`;
    this.popup.style.top = `${y - panelRect.top}px`;
    this.popup.style.display = "block";

    // Ensure popup doesn't overflow viewport
    requestAnimationFrame(() => {
      if (!this.popup) return;
      const popupRect = this.popup.getBoundingClientRect();

      // Check right overflow
      if (popupRect.right > window.innerWidth - 8) {
        this.popup.style.left = `${window.innerWidth - popupRect.width - panelRect.left - 8}px`;
      }

      // Check bottom overflow - show above cursor if needed
      if (popupRect.bottom > window.innerHeight - 8) {
        const lineHeight = 19.5;
        this.popup.style.top = `${y - panelRect.top - popupRect.height - lineHeight}px`;
      }
    });
  }

  // =========================================================================
  // Private Methods - Selection & Accept
  // =========================================================================

  /**
   * Select an autocomplete item by index
   */
  private selectItem(index: number): void {
    if (!this.popup) return;

    // Update visual selection
    const items = this.popup.querySelectorAll(".autocomplete-item");
    items.forEach((item, i) => {
      item.classList.toggle("selected", i === index);
    });

    this.selectedIndex = index;

    // Scroll into view if needed
    const selectedItem = items[index] as HTMLElement;
    if (selectedItem) {
      selectedItem.scrollIntoView({ block: "nearest" });
    }
  }

  /**
   * Accept the selected or specified autocomplete suggestion
   */
  private accept(index?: number): void {
    const idx = index ?? this.selectedIndex;
    const suggestion = this.items[idx];
    if (!suggestion) {
      this.hide();
      return;
    }

    // Find the word being typed (to replace it)
    const value = this.editor.value;
    const cursorPos = this.editor.selectionStart;

    // Find word start (go back until non-identifier char)
    let wordStart = cursorPos;
    while (wordStart > 0 && /[a-zA-Z0-9_]/.test(value[wordStart - 1] ?? "")) {
      wordStart--;
    }

    // Replace the partial word with the completion
    const before = value.substring(0, wordStart);
    const after = value.substring(cursorPos);
    const insertText = suggestion.insertText;

    this.editor.value = before + insertText + after;

    // Set cursor after inserted text
    const newCursorPos = wordStart + insertText.length;
    this.editor.selectionStart = this.editor.selectionEnd = newCursorPos;

    // Trigger input event to update syntax highlighting
    this.editor.dispatchEvent(new Event("input", { bubbles: true }));

    this.hide();
    this.editor.focus();
  }

  // =========================================================================
  // Private Methods - Helpers
  // =========================================================================

  /**
   * Get icon for suggestion kind
   */
  private getKindIcon(kind: AutocompleteSuggestion["kind"]): string {
    switch (kind) {
      case "function": return "ƒ";
      case "property": return "●";
      case "variable": return "x";
      case "keyword": return "◆";
      case "module": return "◫";
      case "class": return "◇";
      case "text": return "T";
      case "path": return "/";
      default: return "·";
    }
  }

  /**
   * Sort suggestions by type correctness (Phase 4b)
   * Order: correct > correctFunctionResult > none
   */
  private sortByTypeCorrectness(
    suggestions: AutocompleteSuggestion[]
  ): AutocompleteSuggestion[] {
    return [...suggestions].sort((a, b) => {
      const scoreA = this.getTypeCorrectScore(a.typeCorrect);
      const scoreB = this.getTypeCorrectScore(b.typeCorrect);
      // Higher score first
      return scoreB - scoreA;
    });
  }

  /**
   * Get numeric score for type correctness (for sorting)
   */
  private getTypeCorrectScore(typeCorrect: AutocompleteSuggestion["typeCorrect"]): number {
    switch (typeCorrect) {
      case "correct": return 2;
      case "correctFunctionResult": return 1;
      default: return 0;
    }
  }
}
