module(
    name = "cells",
    version = "0.0.1",
)

# Platforms for OS-specific configurations
bazel_dep(name = "platforms", version = "0.0.11")

# Google Test
bazel_dep(name = "googletest", version = "1.14.0.bcr.1")

# Native XLSX parsing - XML parser
bazel_dep(name = "pugixml", version = "1.14")

# Hedron's Compile Commands Extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    commit = "1e08f8e0507b6b6b1f4416a9a22cf5c28beaba93",
)
