filegroup(
    name = "sample_cells_files",
    srcs = glob(["*.cells"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sample_csv_files",
    srcs = glob(["csv/*.csv"]) + glob(["csv/*.tsv"]),
    visibility = ["//visibility:public"],
)
