cc_binary(
    name = "cells",
    srcs = [
        "main.cc",
        "options.h",
    ],
    deps = [
        "//core/cells:csv_reader",
        "//core/cells:model",
        "//core/cells:parser",
        "//core/cells:serializer",
    ],
)
