filegroup(
    name = "sample_zcd_files",
    srcs = glob(["*.zcd"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sample_csv_files",
    srcs = glob(["csv/*.csv"]) + glob(["csv/*.tsv"]),
    visibility = ["//visibility:public"],
)
